function generateLeavePDF(res, leave, student) {
  const PDFDocument = require('pdfkit');
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=leave_${leave.id}.pdf`);
  doc.pipe(res);

  // Header bar
  doc.rect(0, 0, doc.page.width, 80).fill('#1e40af');
  doc.fillColor('white').fontSize(22).font('Helvetica-Bold')
    .text('COLLEGE LEAVE MANAGEMENT SYSTEM', 50, 20, { align: 'center' });
  doc.fontSize(11).font('Helvetica').text('Official Leave Application Form', 50, 50, { align: 'center' });

  doc.fillColor('#111').moveDown(3);

  // Leave ID badge
  doc.fontSize(10).fillColor('#6b7280').text(`Leave ID: #${leave.id}   |   Applied: ${new Date(leave.createdAt).toLocaleDateString()}`, { align: 'right' });
  doc.moveDown(0.5);

  // Status badge
  const statusColors = { approved: '#16a34a', rejected: '#dc2626', pending_hod: '#d97706', pending_principal: '#2563eb', cancelled: '#6b7280' };
  const statusColor = statusColors[leave.status] || '#6b7280';
  doc.roundedRect(50, doc.y, 120, 24, 4).fill(statusColor);
  doc.fillColor('white').fontSize(11).font('Helvetica-Bold')
    .text(leave.status.replace('_', ' ').toUpperCase(), 50, doc.y - 20, { width: 120, align: 'center' });
  doc.moveDown(1.5);

  // Section helper
  function section(title) {
    doc.fillColor('#1e40af').fontSize(13).font('Helvetica-Bold').text(title);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#1e40af').lineWidth(1).stroke();
    doc.moveDown(0.4);
    doc.fillColor('#111').fontSize(11).font('Helvetica');
  }

  function row(label, value) {
    doc.font('Helvetica-Bold').text(`${label}: `, { continued: true }).font('Helvetica').text(value || '—');
  }

  // Student Info
  section('Student Information');
  row('Name', `${student?.firstName || ''} ${student?.lastName || ''}`);
  row('Email', student?.email || '');
  row('Phone', student?.phone || '');
  row('Department', student?.department?.name || '');
  row('Section', student?.section?.name || '');
  doc.moveDown(0.8);

  // Leave Details
  section('Leave Details');
  row('Leave Type', leave.leaveType || leave.leaveTypeInfo?.name || '');
  row('From', leave.startDate);
  row('To', leave.endDate);
  row('Total Days', String(leave.totalDays || ''));
  doc.moveDown(0.4);
  doc.font('Helvetica-Bold').text('Reason:');
  doc.font('Helvetica').text(leave.reason || '—', { indent: 10 });
  doc.moveDown(0.8);

  // Approval Trail
  section('Approval Trail');
  // HOD
  doc.font('Helvetica-Bold').text('HOD Review:');
  if (leave.hodId) {
    row('  HOD', `${leave.hod?.firstName || ''} ${leave.hod?.lastName || ''}`);
    row('  Action', leave.status === 'pending_principal' || leave.status === 'approved' ? 'Approved & Forwarded' : 'Rejected');
    row('  Remarks', leave.hodRemarks || 'None');
    row('  Date', leave.hodActionAt ? new Date(leave.hodActionAt).toLocaleString() : '—');
  } else {
    doc.font('Helvetica').fillColor('#6b7280').text('  Pending HOD review');
    doc.fillColor('#111');
  }
  doc.moveDown(0.4);
  // Principal
  doc.font('Helvetica-Bold').text('Principal Review:');
  if (leave.principalId) {
    row('  Principal', `${leave.principal?.firstName || ''} ${leave.principal?.lastName || ''}`);
    row('  Action', leave.status === 'approved' ? 'Approved' : 'Rejected');
    row('  Remarks', leave.principalRemarks || 'None');
    row('  Date', leave.principalActionAt ? new Date(leave.principalActionAt).toLocaleString() : '—');
  } else {
    doc.font('Helvetica').fillColor('#6b7280').text('  Pending Principal review');
    doc.fillColor('#111');
  }
  doc.moveDown(1.5);

  // Signature blocks
  const sigY = doc.y;
  const pageW = doc.page.width - 100;
  const col = pageW / 3;

  ['Student Signature', 'HOD Signature', 'Principal Signature'].forEach((label, i) => {
    const x = 50 + i * (col + 10);
    doc.moveTo(x, sigY + 40).lineTo(x + col - 10, sigY + 40).strokeColor('#374151').lineWidth(0.5).stroke();
    doc.fillColor('#374151').fontSize(9).text(label, x, sigY + 44, { width: col - 10, align: 'center' });
  });

  doc.moveDown(4);

  // Footer
  doc.fontSize(8).fillColor('#9ca3af')
    .text(`Generated by CLMS on ${new Date().toLocaleString()} — This is a system-generated document.`, { align: 'center' });

  doc.end();
}

module.exports = { generateLeavePDF };
